# ==============================
# Database Configuration (MySQL)
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/moviemanagementdb
spring.datasource.username=root
spring.datasource.password=Pass@123

# ==============================
# Hibernate / JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Server Port
# ==============================
server.port=8081

# ==============================
# Swagger / OpenAPI Config
# ==============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# keep default paths
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
